ALTER TABLE members 
ADD committee_tally int; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89449; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25470; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88786; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88325; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88397; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 59265; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 89374; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88982; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89211; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 86260; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89032; 
UPDATE members 
SET committee_tally = cast (4 as int) 
WHERE members.id = 88775; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 35897; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88687; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89167; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89130; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88532; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88368; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88807; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 58707; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71357; 
UPDATE members 
SET committee_tally = cast (3 as int) 
WHERE members.id = 88756; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88360; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 35397; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88357; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88761; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 1825; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 31664; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 35886; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88994; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 1589; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 7251; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71447; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88299; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88333; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25465; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 89045; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89084; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88953; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89010; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89346; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71902; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89339; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 58878; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88813; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25461; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25468; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88950; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89258; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89527; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25493; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 48292; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 35904; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88323; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88802; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88799; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89109; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 23915; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 43; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88694; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89139; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88468; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 35539; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88925; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89466; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 54325; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88999; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89294; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 63592; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 89274; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88340; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88283; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25456; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 69488; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71986; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25446; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 15975; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88827; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 35699; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71434; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89018; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88660; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 89288; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88419; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 35389; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25520; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89179; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25449; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 31796; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88296; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25486; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 51; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 59325; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 89027; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89144; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71786; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88881; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88703; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89116; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 36037; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88535; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71599; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88617; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 89304; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88692; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88784; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25467; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 72035; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89383; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88860; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88578; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 35309; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 59226; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88929; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 9137; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88679; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 31098; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 1806; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71692; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 59148; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88601; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88365; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71702; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88745; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 1209; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 31765; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88934; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89219; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 84672; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88346; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88558; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89020; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88849; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 59293; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 820; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 60078; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25475; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89279; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 1809; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71995; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 71454; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88521; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88852; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 86261; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 59110; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 89327; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88446; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88748; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88874; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89198; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88726; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 873; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 35320; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 35351; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 63908; 
UPDATE members 
SET committee_tally = cast (3 as int) 
WHERE members.id = 88973; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88917; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 198; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25489; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 89407; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25524; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88442; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 1832; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88884; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88627; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71368; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88738; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 25522; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 58858; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 72773; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88600; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88316; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88938; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89200; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89486; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 58806; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88698; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 71738; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88742; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88867; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 88541; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 59156; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 35873; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 71337; 
UPDATE members 
SET committee_tally = cast (2 as int) 
WHERE members.id = 88858; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89095; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 764; 
UPDATE members 
SET committee_tally = cast (1 as int) 
WHERE members.id = 89098; 
