ALTER TABLE members 
ADD column did_not_vote_score decimal(10,1) 
 ;Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88422;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 376;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 88651;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88605;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 88538;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88544;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88595;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 413;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 88485;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88552;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89156;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 72029;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 35607;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 25446;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 25447;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 1795;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89294;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 86261;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 59110;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 35309;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88541;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 25475;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 35389;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 59156;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 35320;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88674;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 25483;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 35897;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 25486;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 25488;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88404;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 15975;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89219;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88535;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89150;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 89249;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 59226;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 48292;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 84672;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 35904;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 25501;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 1809;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 63908;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89226;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88938;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 89407;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 35397;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 89200;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 1733;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 71945;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 59148;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 89167;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89130;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 1302;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 35699;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89095;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89136;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 35857;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 25516;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 38633;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 71786;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 89139;
Update members 
Set did_not_vote_score = cast ('2.0' as decimal(10,1))
WHERE members.id = 35600;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 25520;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 891;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 7251;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89179;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 35539;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 59265;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 25522;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88917;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 820;
Update members 
Set did_not_vote_score = cast ('2.0' as decimal(10,1))
WHERE members.id = 88679;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 1287;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 72773;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 71454;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 25524;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 54325;
Update members 
Set did_not_vote_score = cast ('2.0' as decimal(10,1))
WHERE members.id = 88600;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 1827;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 71902;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 59235;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 1209;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 58878;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 25454;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88770;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 89109;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 31664;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 69488;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 1832;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 35724;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 71986;
Update members 
Set did_not_vote_score = cast ('2.0' as decimal(10,1))
WHERE members.id = 89198;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 31715;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 25461;
Update members 
Set did_not_vote_score = cast ('2.0' as decimal(10,1))
WHERE members.id = 25462;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 31765;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 25465;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 88742;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89211;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 89098;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 25467;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 35886;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89333;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89084;
Update members 
Set did_not_vote_score = cast ('2.0' as decimal(10,1))
WHERE members.id = 89116;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 30812;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 86260;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 72035;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 2897;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89258;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 89535;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88671;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 89527;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 89449;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89383;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88860;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88419;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88867;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 1796;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 25471;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88578;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89236;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 873;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 992;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88449;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88934;
Update members 
Set did_not_vote_score = cast ('2.0' as decimal(10,1))
WHERE members.id = 88961;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 89147;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 88786;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 88775;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 58707;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 74;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 86786;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 89059;
Update members 
Set did_not_vote_score = cast ('0.7' as decimal(10,1))
WHERE members.id = 51;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 71270;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 89000;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88633;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 86249;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88953;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88350;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 1804;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88994;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88884;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88355;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 31098;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88453;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88627;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 460;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88756;
Update members 
Set did_not_vote_score = cast ('0.7' as decimal(10,1))
WHERE members.id = 84660;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 89408;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 31119;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 58877;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88721;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 43;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89010;
Update members 
Set did_not_vote_score = cast ('2.0' as decimal(10,1))
WHERE members.id = 88515;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88683;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88687;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 1806;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89027;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88478;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88325;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88360;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 88323;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 71692;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 58519;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88827;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88316;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88346;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 84665;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 1589;
Update members 
Set did_not_vote_score = cast ('0.7' as decimal(10,1))
WHERE members.id = 89279;
Update members 
Set did_not_vote_score = cast ('0.7' as decimal(10,1))
WHERE members.id = 10524;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 88802;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 89370;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 1265;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88715;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88504;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88694;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88984;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89274;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88370;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 89111;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 25508;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88558;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 89020;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88292;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 71337;
Update members 
Set did_not_vote_score = cast ('0.7' as decimal(10,1))
WHERE members.id = 88384;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 13218;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88340;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88929;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 89144;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88849;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 88705;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88501;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 30552;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88601;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 88394;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 1813;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88460;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 88973;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88446;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88894;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 89018;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88532;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 88357;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88368;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88761;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88365;
Update members 
Set did_not_vote_score = cast ('0.7' as decimal(10,1))
WHERE members.id = 33;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88468;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88748;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88397;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 71599;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 1817;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 71602;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 88283;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 9486;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 957;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88892;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 59293;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89374;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 58621;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88738;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 89037;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88660;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88922;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88992;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88308;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 35950;
Update members 
Set did_not_vote_score = cast ('0.7' as decimal(10,1))
WHERE members.id = 58806;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 709;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88925;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 58858;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88881;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 88299;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 89466;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 198;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 1825;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 71702;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88364;
Update members 
Set did_not_vote_score = cast ('0.7' as decimal(10,1))
WHERE members.id = 88835;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 71529;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 88493;
Update members 
Set did_not_vote_score = cast ('2.0' as decimal(10,1))
WHERE members.id = 89272;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 25449;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 1760;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88623;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88617;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 25451;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 88521;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 25452;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 71718;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89304;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88982;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88698;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 88807;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 89497;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 88333;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 88692;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 89339;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 25453;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88649;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88799;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88874;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 1787;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88442;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88944;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89288;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88703;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88858;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 25456;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 89163;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 88999;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88852;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 88813;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 88726;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 88784;
Update members 
Set did_not_vote_score = cast ('0.7' as decimal(10,1))
WHERE members.id = 1665;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 58733;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89045;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 71738;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 54434;
Update members 
Set did_not_vote_score = cast ('0.7' as decimal(10,1))
WHERE members.id = 88910;
Update members 
Set did_not_vote_score = cast ('0.7' as decimal(10,1))
WHERE members.id = 88296;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 89300;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 89494;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 25468;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 88832;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 88950;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 25470;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 36037;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 71560;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89090;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 89032;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 89354;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 58775;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 71395;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 71357;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 89327;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 23915;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 35351;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 25489;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 25493;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 59325;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 63592;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 71368;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 35873;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 71553;
Update members 
Set did_not_vote_score = cast ('2.0' as decimal(10,1))
WHERE members.id = 88780;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 71995;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 89012;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 31289;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89263;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 89065;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 16399;
Update members 
Set did_not_vote_score = cast ('6.0' as decimal(10,1))
WHERE members.id = 89346;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 71434;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89269;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 89486;
Update members 
Set did_not_vote_score = cast ('4.7' as decimal(10,1))
WHERE members.id = 9137;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 764;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 232;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 26684;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 71447;
Update members 
Set did_not_vote_score = cast ('8.7' as decimal(10,1))
WHERE members.id = 71350;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 88745;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 60078;
Update members 
Set did_not_vote_score = cast ('0' as decimal(10,1))
WHERE members.id = 71482;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 53569;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 89281;
Update members 
Set did_not_vote_score = cast ('7.3' as decimal(10,1))
WHERE members.id = 31701;
Update members 
Set did_not_vote_score = cast ('3.3' as decimal(10,1))
WHERE members.id = 88488;
Update members 
Set did_not_vote_score = cast ('10.0' as decimal(10,1))
WHERE members.id = 31796;
