UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 89156; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 72029; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35607; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89258; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89535; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88671; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25446; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25447; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89527; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89449; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1795; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25470; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89294; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89383; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88860; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 36037; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71560; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88419; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88867; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 1796; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 25471; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 86261; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 88422; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88578; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 376; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89236; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 873; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 992; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89090; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 59110; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35309; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88541; 
UPDATE members 
SET sponsored_bill_tally = cast (2 as int) 
WHERE members.id = 25475; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88449; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88934; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89032; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88961; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 35389; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89354; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 59156; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89147; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88786; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35320; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88651; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 58775; 
UPDATE members 
SET sponsored_bill_tally = cast (2 as int) 
WHERE members.id = 71395; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88674; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88775; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 58707; 
UPDATE members 
SET sponsored_bill_tally = cast (5 as int) 
WHERE members.id = 74; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 71357; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 25483; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 86786; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35897; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89327; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 23915; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89059; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25486; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 51; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71270; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89000; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88633; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 86249; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88953; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25488; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35351; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25489; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88404; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 15975; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89219; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88350; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25493; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1804; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88994; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88884; 
UPDATE members 
SET sponsored_bill_tally = cast (8 as int) 
WHERE members.id = 59325; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88355; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88535; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 31098; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88453; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88627; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 460; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89150; 
UPDATE members 
SET sponsored_bill_tally = cast (4 as int) 
WHERE members.id = 89249; 
UPDATE members 
SET sponsored_bill_tally = cast (2 as int) 
WHERE members.id = 63592; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 59226; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88756; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71368; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 84660; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89408; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 31119; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 58877; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 35873; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71553; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88780; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88721; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 43; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 48292; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89010; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88515; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88683; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 88687; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1806; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89027; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 84672; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35904; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88478; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88325; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25501; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88360; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 88323; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71692; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 58519; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88605; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 88827; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88346; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88316; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 84665; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1589; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89279; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1809; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 10524; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 71995; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 63908; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89226; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 88802; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88538; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88938; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89407; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89370; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1265; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88715; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35397; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88504; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88694; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88984; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89012; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89200; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89274; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1733; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88370; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 89111; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71945; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 59148; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25508; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88558; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 31289; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 89020; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88292; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71337; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89167; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89263; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89065; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88384; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 13218; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88340; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88929; 
UPDATE members 
SET sponsored_bill_tally = cast (3 as int) 
WHERE members.id = 16399; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89144; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89130; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1302; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35699; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88849; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88705; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89095; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89136; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89346; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35857; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88501; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 30552; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 88601; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25516; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88394; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71434; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 38633; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1813; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88460; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88973; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71786; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88446; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88894; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89018; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 89139; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88532; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 35600; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88357; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88368; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88761; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88365; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25520; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 33; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 89269; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 891; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88468; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 7251; 
UPDATE members 
SET sponsored_bill_tally = cast (2 as int) 
WHERE members.id = 89486; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88748; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88544; 
UPDATE members 
SET sponsored_bill_tally = cast (4 as int) 
WHERE members.id = 9137; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88397; 
UPDATE members 
SET sponsored_bill_tally = cast (2 as int) 
WHERE members.id = 764; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 71599; 
UPDATE members 
SET sponsored_bill_tally = cast (3 as int) 
WHERE members.id = 2897; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 1817; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89179; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35539; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71602; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88283; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 9486; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 957; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88892; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 59293; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 59265; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89374; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 58621; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88738; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 89037; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 25522; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88660; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88922; 
UPDATE members 
SET sponsored_bill_tally = cast (3 as int) 
WHERE members.id = 232; 
UPDATE members 
SET sponsored_bill_tally = cast (2 as int) 
WHERE members.id = 88992; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88308; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 26684; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35950; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71447; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 58806; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88917; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 709; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 820; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88679; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1287; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88925; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 58858; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88881; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88299; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 72773; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89466; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 198; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71454; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88595; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1825; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71702; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88364; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88835; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71529; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 413; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25524; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88493; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71350; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89272; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 54325; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88745; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 60078; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25449; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88600; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1760; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1827; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71902; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 59235; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88623; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1209; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88617; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25451; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88521; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25452; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71718; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89304; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88982; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 71482; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88698; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88807; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89497; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88333; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88692; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 53569; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89339; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 58878; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25453; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25454; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88649; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88770; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88799; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88874; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1787; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88442; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88944; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89109; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 31664; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89288; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88703; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 88858; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 25456; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89163; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 69488; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88999; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1832; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88852; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 35724; 
UPDATE members 
SET sponsored_bill_tally = cast (1 as int) 
WHERE members.id = 88485; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89281; 
UPDATE members 
SET sponsored_bill_tally = cast (2 as int) 
WHERE members.id = 31701; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 71986; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89198; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 31715; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88813; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 88726; 
UPDATE members 
SET sponsored_bill_tally = cast (2 as int) 
WHERE members.id = 88992; 
UPDATE members 
SET sponsored_bill_tally = cast (2 as int) 
WHERE members.id = 58733; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 89059; 
UPDATE members 
SET sponsored_bill_tally = cast (2 as int) 
WHERE members.id = 89494; 
UPDATE members 
SET sponsored_bill_tally = cast (0 as int) 
WHERE members.id = 1665; 
